# Batch size 10 -> 32
# CONCEPT OVERLAP @ k=10: -> Acc: 72.9631%, MAP: 29.8085%, MAR: 0.5888%, F1: 1.1549%

download:
  text_preprocess: https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3
  text_transformer: https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-512_A-8/2
  img_preprocess: convnext
  img_supernet: ConvNeXtTiny

model:
  img_input_shape:
    - 128
    - 128
    - 3
  embed_dim: 32
  learning_rate: 0.00002
  weight_decay: 0.1
  weights_path: ../Models/Weights/v2.1.h5