# Efficientnet and larger learning rate
# CONCEPT OVERLAP @ k=10: -> Acc: 80.9787%, MAP: 33.9562%, MAR: 0.7607%, F1: 1.488%

download:
  text_preprocess: https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3
  text_transformer:  https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-512_A-8/1
  img_preprocess: efficientnet
  img_supernet: EfficientNetV2S

model:
  img_input_shape:
    - 128
    - 128
    - 3
  embed_dim: 32
  learning_rate: 0.0001
  weight_decay: 0.1
  grayscale_preprocess: True
  weights_path: ../Models/Weights/v5.0.h5